name: app-build-action

# 推送 tv_* Tag 时触发
on:
  workflow_dispatch:
  push:
    tags:
      - "tv_*"

jobs:
  build-tv:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      # 签出代码
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master

      # 设置 JAVA 环境
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: "zulu"
          java-version: "17"
          cache: "gradle"

      # 设置 Flutter
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          cache: true

      # 更新 Flutter packages
      - name: Restore packages
        working-directory: simple_live_tv_app
        run: flutter pub get

      # 打包 APK
      - name: Build APK
        working-directory: simple_live_tv_app
        run: flutter build apk --release --split-per-abi

      # 上传 APK 至 Artifacts
      - name: Upload APK to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: android_tv
          path: |
            simple_live_tv_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
            simple_live_tv_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            simple_live_tv_app/build/app/outputs/flutter-apk/app-x86_64-release.apk

      # 读取版本信息
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: assets/tv_app_version.json

      # 输出版本信息
      - name: Echo version
        run: |
          echo "Version: ${{ fromJson(steps.version.outputs.content).version }}"
          echo "Description: ${{ fromJson(steps.version.outputs.content).version_desc }}"

      # 上传至 GitHub Release
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ fromJson(steps.version.outputs.content).version }}"
          body: |
            # Android TV

            ${{ fromJson(steps.version.outputs.content).version_desc }}
          prerelease: ${{ fromJson(steps.version.outputs.content).prerelease }}
          token: ${{ github.token }}
          files: |
            simple_live_tv_app/build/app/outputs/flutter-apk/app-x86_64-release.apk
            simple_live_tv_app/build/app/outputs/flutter-apk/app-arm64-v8a-release.apk
            simple_live_tv_app/build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk

      # 完成
      - name: Build status
        run: echo "🍏 This job's status is ${{ job.status }}."
